/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package User.Registration.JUnit.Test;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
